[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
startCommand = "python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[[services]]
name = "telegram-agent"

[services.source]
repo = "."

[services.variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"