[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[[services]]
name = "telegram-agent"

[services.source]
repo = "."

[services.variables]
PYTHONUNBUFFERED = "1"